ALTER TABLE student
ADD CONSTRAINT age CHECK (age >= 16),
ALTER COLUMN name SET NOT NULL,
ADD CONSTRAINT name UNIQUE (name),
ALTER COLUMN age SET DEFAULT 20;

ALTER TABLE faculty ADD CONSTRAINT name UNIQUE (name, color);